### ISSUE TITLE
Curated Gallery

### ISSUE THREAD

**Issue by PWhiddy** [bnanner/shader-park-website#17]
Should be easiest to reuse UI for marking examples

**Comment by PWhiddy** [comment]
Also allow us to mark very sluggish/browser crashing sculptures as "hidden" from any public display. (eventually this could happen automatically)

**Comment by PWhiddy** [comment]
We already have a "featured" toggle when logged in as admin I think? so just needs a custom route. Feel free to bump to stretch if that seems like a lot

**Comment by torinmb** [comment]
We can add featured sculptures through the DB
